CME Signed Requests Tool
GoogleCloudPlatform/DIY-Tools pull request #20
Opened 2022-05-17 08:50 UTC by msampathkumar

CME Signed Requests Tools is CLI tool for generating Signed URL Requests for Google Cloud Media Edge.

Written in Go, this is a simple tool & does not need/depends on any other tools. All Generated Signed URL Requests(text) are displayed to STDOUT

2022-05-19 13:23 UTC, goog-lukemc commented on signed-requests/README.md
> +
Start the instructions from Git Clone and walk the user to success. See GCP-Data-Drive readme as an example.

2022-05-19 13:30 UTC, goog-lukemc requested changes

2022-05-19 13:30 UTC, goog-lukemc commented on signed-requests/README.md
> +# signedrequests
See single comments

2022-07-06 13:13 UTC, goog-lukemc approved these changes
LGTM

2022-07-06 13:13 UTC, merged

2022-07-11 13:50 UTC, msampathkumar commented
Thank you Luke :)